package adventofcode_2021;


import utils.AdventOfCodeUtil;

public class AdventOfCode_2021_02 {

	static String input = "forward 7\n" +
			"down 2\n" +
			"forward 7\n" +
			"down 6\n" +
			"forward 1\n" +
			"forward 7\n" +
			"down 3\n" +
			"up 5\n" +
			"forward 7\n" +
			"forward 6\n" +
			"down 8\n" +
			"down 1\n" +
			"up 5\n" +
			"up 1\n" +
			"down 2\n" +
			"forward 8\n" +
			"forward 3\n" +
			"down 8\n" +
			"down 9\n" +
			"down 1\n" +
			"forward 4\n" +
			"down 8\n" +
			"down 7\n" +
			"forward 3\n" +
			"up 5\n" +
			"up 3\n" +
			"forward 9\n" +
			"forward 5\n" +
			"forward 5\n" +
			"down 9\n" +
			"up 2\n" +
			"down 4\n" +
			"up 4\n" +
			"down 9\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 7\n" +
			"forward 4\n" +
			"down 2\n" +
			"down 6\n" +
			"up 3\n" +
			"down 2\n" +
			"down 4\n" +
			"up 5\n" +
			"forward 7\n" +
			"up 8\n" +
			"down 4\n" +
			"forward 8\n" +
			"down 5\n" +
			"forward 1\n" +
			"forward 3\n" +
			"up 9\n" +
			"forward 5\n" +
			"down 4\n" +
			"forward 6\n" +
			"forward 2\n" +
			"up 3\n" +
			"down 5\n" +
			"down 6\n" +
			"forward 8\n" +
			"up 6\n" +
			"up 9\n" +
			"down 8\n" +
			"down 2\n" +
			"down 6\n" +
			"forward 2\n" +
			"forward 8\n" +
			"forward 1\n" +
			"forward 5\n" +
			"forward 3\n" +
			"down 8\n" +
			"down 5\n" +
			"forward 3\n" +
			"up 7\n" +
			"down 9\n" +
			"up 9\n" +
			"forward 7\n" +
			"forward 6\n" +
			"forward 4\n" +
			"down 5\n" +
			"forward 1\n" +
			"down 9\n" +
			"forward 9\n" +
			"forward 6\n" +
			"down 8\n" +
			"down 5\n" +
			"forward 5\n" +
			"forward 4\n" +
			"forward 3\n" +
			"up 6\n" +
			"up 7\n" +
			"forward 2\n" +
			"up 2\n" +
			"up 9\n" +
			"forward 8\n" +
			"up 3\n" +
			"forward 8\n" +
			"down 8\n" +
			"forward 1\n" +
			"forward 7\n" +
			"forward 4\n" +
			"down 5\n" +
			"forward 8\n" +
			"down 2\n" +
			"down 2\n" +
			"down 3\n" +
			"forward 3\n" +
			"forward 3\n" +
			"up 3\n" +
			"forward 4\n" +
			"up 9\n" +
			"up 8\n" +
			"forward 1\n" +
			"down 8\n" +
			"up 6\n" +
			"down 5\n" +
			"up 3\n" +
			"up 2\n" +
			"forward 1\n" +
			"up 8\n" +
			"down 7\n" +
			"up 5\n" +
			"down 2\n" +
			"forward 5\n" +
			"down 3\n" +
			"down 1\n" +
			"forward 2\n" +
			"forward 6\n" +
			"forward 7\n" +
			"forward 1\n" +
			"forward 5\n" +
			"forward 4\n" +
			"down 9\n" +
			"forward 6\n" +
			"down 9\n" +
			"up 8\n" +
			"forward 9\n" +
			"forward 5\n" +
			"up 2\n" +
			"up 7\n" +
			"up 2\n" +
			"down 1\n" +
			"down 7\n" +
			"down 1\n" +
			"forward 2\n" +
			"down 8\n" +
			"down 3\n" +
			"forward 1\n" +
			"down 5\n" +
			"forward 7\n" +
			"forward 5\n" +
			"forward 6\n" +
			"up 6\n" +
			"forward 6\n" +
			"forward 1\n" +
			"down 2\n" +
			"forward 5\n" +
			"down 7\n" +
			"up 1\n" +
			"down 5\n" +
			"down 4\n" +
			"down 8\n" +
			"up 2\n" +
			"down 2\n" +
			"up 6\n" +
			"forward 2\n" +
			"down 2\n" +
			"up 9\n" +
			"down 7\n" +
			"down 3\n" +
			"down 6\n" +
			"forward 5\n" +
			"up 5\n" +
			"forward 2\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 3\n" +
			"forward 4\n" +
			"forward 4\n" +
			"down 6\n" +
			"down 2\n" +
			"down 4\n" +
			"forward 6\n" +
			"down 2\n" +
			"down 8\n" +
			"up 2\n" +
			"forward 9\n" +
			"down 8\n" +
			"forward 4\n" +
			"down 2\n" +
			"up 4\n" +
			"down 6\n" +
			"forward 3\n" +
			"forward 2\n" +
			"forward 7\n" +
			"down 7\n" +
			"forward 3\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 6\n" +
			"down 4\n" +
			"forward 4\n" +
			"down 6\n" +
			"down 8\n" +
			"down 4\n" +
			"forward 3\n" +
			"up 5\n" +
			"up 4\n" +
			"up 9\n" +
			"forward 9\n" +
			"down 1\n" +
			"forward 3\n" +
			"forward 9\n" +
			"up 3\n" +
			"down 5\n" +
			"forward 2\n" +
			"down 9\n" +
			"down 9\n" +
			"forward 1\n" +
			"forward 4\n" +
			"forward 8\n" +
			"forward 9\n" +
			"down 4\n" +
			"forward 3\n" +
			"down 3\n" +
			"forward 9\n" +
			"down 1\n" +
			"down 3\n" +
			"down 9\n" +
			"down 3\n" +
			"down 2\n" +
			"down 1\n" +
			"up 2\n" +
			"down 3\n" +
			"up 7\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 6\n" +
			"down 1\n" +
			"down 7\n" +
			"down 7\n" +
			"up 7\n" +
			"forward 8\n" +
			"down 1\n" +
			"down 7\n" +
			"down 8\n" +
			"up 4\n" +
			"down 6\n" +
			"down 7\n" +
			"forward 5\n" +
			"down 9\n" +
			"forward 2\n" +
			"down 6\n" +
			"down 8\n" +
			"down 5\n" +
			"down 4\n" +
			"forward 8\n" +
			"down 4\n" +
			"forward 8\n" +
			"down 3\n" +
			"down 6\n" +
			"forward 6\n" +
			"forward 1\n" +
			"up 5\n" +
			"down 2\n" +
			"down 2\n" +
			"forward 7\n" +
			"forward 1\n" +
			"up 3\n" +
			"down 6\n" +
			"down 3\n" +
			"down 9\n" +
			"up 6\n" +
			"forward 4\n" +
			"down 1\n" +
			"forward 4\n" +
			"up 3\n" +
			"forward 6\n" +
			"down 7\n" +
			"down 2\n" +
			"up 3\n" +
			"down 1\n" +
			"up 7\n" +
			"down 7\n" +
			"forward 5\n" +
			"up 9\n" +
			"up 1\n" +
			"up 2\n" +
			"forward 4\n" +
			"forward 9\n" +
			"up 3\n" +
			"down 8\n" +
			"up 2\n" +
			"down 9\n" +
			"forward 8\n" +
			"up 2\n" +
			"down 5\n" +
			"up 5\n" +
			"down 2\n" +
			"up 8\n" +
			"down 6\n" +
			"down 8\n" +
			"up 7\n" +
			"forward 9\n" +
			"forward 6\n" +
			"forward 5\n" +
			"forward 8\n" +
			"forward 7\n" +
			"down 2\n" +
			"forward 1\n" +
			"forward 6\n" +
			"down 3\n" +
			"down 7\n" +
			"up 1\n" +
			"forward 7\n" +
			"up 7\n" +
			"down 2\n" +
			"down 9\n" +
			"up 4\n" +
			"forward 2\n" +
			"down 3\n" +
			"up 8\n" +
			"up 3\n" +
			"down 9\n" +
			"down 2\n" +
			"forward 4\n" +
			"forward 9\n" +
			"forward 8\n" +
			"forward 2\n" +
			"up 2\n" +
			"forward 3\n" +
			"forward 8\n" +
			"down 2\n" +
			"down 4\n" +
			"up 8\n" +
			"up 2\n" +
			"forward 4\n" +
			"forward 7\n" +
			"up 8\n" +
			"forward 8\n" +
			"forward 1\n" +
			"forward 9\n" +
			"down 9\n" +
			"up 3\n" +
			"forward 9\n" +
			"down 5\n" +
			"down 9\n" +
			"down 2\n" +
			"forward 1\n" +
			"forward 6\n" +
			"forward 3\n" +
			"up 7\n" +
			"down 8\n" +
			"down 2\n" +
			"up 6\n" +
			"down 5\n" +
			"forward 4\n" +
			"up 7\n" +
			"down 5\n" +
			"down 3\n" +
			"forward 5\n" +
			"forward 5\n" +
			"up 4\n" +
			"down 7\n" +
			"down 5\n" +
			"up 1\n" +
			"down 4\n" +
			"down 6\n" +
			"forward 6\n" +
			"forward 3\n" +
			"down 9\n" +
			"forward 6\n" +
			"forward 4\n" +
			"down 8\n" +
			"up 5\n" +
			"down 7\n" +
			"forward 6\n" +
			"forward 7\n" +
			"down 9\n" +
			"forward 3\n" +
			"forward 3\n" +
			"forward 4\n" +
			"down 6\n" +
			"forward 2\n" +
			"forward 9\n" +
			"up 2\n" +
			"forward 7\n" +
			"up 5\n" +
			"forward 6\n" +
			"down 8\n" +
			"down 7\n" +
			"forward 1\n" +
			"down 6\n" +
			"forward 3\n" +
			"down 9\n" +
			"forward 7\n" +
			"forward 2\n" +
			"forward 1\n" +
			"down 9\n" +
			"down 2\n" +
			"up 8\n" +
			"down 1\n" +
			"down 3\n" +
			"up 6\n" +
			"down 5\n" +
			"up 2\n" +
			"down 2\n" +
			"down 8\n" +
			"forward 7\n" +
			"down 8\n" +
			"forward 6\n" +
			"up 5\n" +
			"down 8\n" +
			"down 4\n" +
			"down 1\n" +
			"forward 1\n" +
			"forward 9\n" +
			"down 3\n" +
			"forward 9\n" +
			"up 2\n" +
			"down 2\n" +
			"forward 9\n" +
			"up 2\n" +
			"up 2\n" +
			"down 8\n" +
			"down 1\n" +
			"up 4\n" +
			"down 9\n" +
			"down 6\n" +
			"up 7\n" +
			"down 6\n" +
			"forward 7\n" +
			"forward 3\n" +
			"forward 9\n" +
			"forward 2\n" +
			"down 9\n" +
			"down 8\n" +
			"down 5\n" +
			"forward 4\n" +
			"forward 1\n" +
			"forward 3\n" +
			"forward 3\n" +
			"forward 1\n" +
			"forward 6\n" +
			"forward 7\n" +
			"down 7\n" +
			"down 1\n" +
			"up 4\n" +
			"up 2\n" +
			"forward 9\n" +
			"up 7\n" +
			"down 1\n" +
			"forward 5\n" +
			"down 8\n" +
			"forward 3\n" +
			"down 9\n" +
			"up 4\n" +
			"up 1\n" +
			"forward 7\n" +
			"down 1\n" +
			"forward 4\n" +
			"up 6\n" +
			"down 9\n" +
			"forward 2\n" +
			"forward 7\n" +
			"down 1\n" +
			"forward 2\n" +
			"forward 1\n" +
			"down 2\n" +
			"forward 6\n" +
			"down 4\n" +
			"up 7\n" +
			"down 6\n" +
			"forward 1\n" +
			"down 9\n" +
			"up 8\n" +
			"up 6\n" +
			"forward 4\n" +
			"down 5\n" +
			"up 8\n" +
			"down 5\n" +
			"up 9\n" +
			"forward 1\n" +
			"forward 6\n" +
			"down 4\n" +
			"up 5\n" +
			"forward 4\n" +
			"forward 2\n" +
			"down 6\n" +
			"forward 9\n" +
			"down 7\n" +
			"down 2\n" +
			"forward 1\n" +
			"up 2\n" +
			"forward 4\n" +
			"forward 4\n" +
			"forward 7\n" +
			"down 5\n" +
			"up 1\n" +
			"down 7\n" +
			"down 1\n" +
			"forward 3\n" +
			"forward 6\n" +
			"forward 7\n" +
			"down 5\n" +
			"down 4\n" +
			"down 2\n" +
			"down 3\n" +
			"up 3\n" +
			"forward 7\n" +
			"down 3\n" +
			"up 2\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 4\n" +
			"forward 9\n" +
			"forward 4\n" +
			"forward 2\n" +
			"down 9\n" +
			"forward 1\n" +
			"down 5\n" +
			"forward 3\n" +
			"forward 5\n" +
			"up 7\n" +
			"down 9\n" +
			"up 7\n" +
			"down 5\n" +
			"down 2\n" +
			"up 5\n" +
			"up 1\n" +
			"forward 8\n" +
			"forward 3\n" +
			"up 5\n" +
			"forward 2\n" +
			"down 2\n" +
			"forward 5\n" +
			"forward 3\n" +
			"forward 4\n" +
			"up 4\n" +
			"forward 3\n" +
			"up 4\n" +
			"forward 1\n" +
			"down 2\n" +
			"forward 5\n" +
			"down 9\n" +
			"forward 8\n" +
			"forward 2\n" +
			"forward 5\n" +
			"forward 1\n" +
			"up 3\n" +
			"up 8\n" +
			"forward 2\n" +
			"forward 9\n" +
			"down 7\n" +
			"up 5\n" +
			"up 2\n" +
			"forward 1\n" +
			"forward 4\n" +
			"up 4\n" +
			"forward 5\n" +
			"down 5\n" +
			"forward 5\n" +
			"down 2\n" +
			"down 8\n" +
			"forward 4\n" +
			"down 3\n" +
			"forward 7\n" +
			"down 7\n" +
			"forward 6\n" +
			"down 9\n" +
			"down 2\n" +
			"up 4\n" +
			"up 5\n" +
			"down 2\n" +
			"down 7\n" +
			"forward 3\n" +
			"down 1\n" +
			"down 5\n" +
			"down 6\n" +
			"forward 8\n" +
			"forward 7\n" +
			"down 3\n" +
			"forward 4\n" +
			"forward 8\n" +
			"forward 2\n" +
			"down 8\n" +
			"down 3\n" +
			"forward 8\n" +
			"down 2\n" +
			"up 2\n" +
			"forward 3\n" +
			"up 2\n" +
			"down 7\n" +
			"down 4\n" +
			"forward 8\n" +
			"forward 7\n" +
			"down 9\n" +
			"forward 7\n" +
			"down 8\n" +
			"up 3\n" +
			"forward 1\n" +
			"up 5\n" +
			"forward 6\n" +
			"down 7\n" +
			"forward 8\n" +
			"forward 3\n" +
			"forward 1\n" +
			"forward 5\n" +
			"down 8\n" +
			"up 8\n" +
			"forward 9\n" +
			"down 7\n" +
			"up 8\n" +
			"up 8\n" +
			"forward 9\n" +
			"up 6\n" +
			"forward 2\n" +
			"down 8\n" +
			"forward 6\n" +
			"down 6\n" +
			"down 6\n" +
			"forward 8\n" +
			"up 9\n" +
			"forward 9\n" +
			"down 8\n" +
			"down 8\n" +
			"forward 3\n" +
			"forward 3\n" +
			"down 8\n" +
			"up 7\n" +
			"down 1\n" +
			"forward 5\n" +
			"up 6\n" +
			"forward 6\n" +
			"up 8\n" +
			"down 7\n" +
			"down 3\n" +
			"down 4\n" +
			"forward 7\n" +
			"down 2\n" +
			"forward 4\n" +
			"forward 6\n" +
			"down 2\n" +
			"down 6\n" +
			"up 2\n" +
			"down 9\n" +
			"down 8\n" +
			"forward 6\n" +
			"up 8\n" +
			"up 4\n" +
			"forward 1\n" +
			"forward 2\n" +
			"down 8\n" +
			"forward 6\n" +
			"down 2\n" +
			"down 7\n" +
			"down 1\n" +
			"down 2\n" +
			"forward 9\n" +
			"forward 5\n" +
			"down 2\n" +
			"down 8\n" +
			"down 9\n" +
			"up 6\n" +
			"forward 6\n" +
			"up 2\n" +
			"down 9\n" +
			"down 4\n" +
			"down 9\n" +
			"up 7\n" +
			"forward 2\n" +
			"up 9\n" +
			"down 7\n" +
			"forward 2\n" +
			"down 7\n" +
			"up 6\n" +
			"down 3\n" +
			"up 1\n" +
			"down 8\n" +
			"down 4\n" +
			"forward 1\n" +
			"up 5\n" +
			"up 4\n" +
			"down 2\n" +
			"down 8\n" +
			"forward 8\n" +
			"forward 7\n" +
			"up 1\n" +
			"down 8\n" +
			"forward 2\n" +
			"forward 7\n" +
			"down 4\n" +
			"forward 4\n" +
			"down 3\n" +
			"down 7\n" +
			"forward 8\n" +
			"down 7\n" +
			"down 3\n" +
			"down 3\n" +
			"forward 8\n" +
			"forward 8\n" +
			"up 1\n" +
			"forward 8\n" +
			"forward 6\n" +
			"down 9\n" +
			"up 1\n" +
			"down 7\n" +
			"down 7\n" +
			"forward 7\n" +
			"forward 7\n" +
			"up 5\n" +
			"down 7\n" +
			"down 6\n" +
			"down 6\n" +
			"forward 8\n" +
			"down 3\n" +
			"forward 8\n" +
			"down 8\n" +
			"forward 7\n" +
			"forward 2\n" +
			"up 6\n" +
			"down 6\n" +
			"down 8\n" +
			"forward 1\n" +
			"forward 8\n" +
			"down 9\n" +
			"down 7\n" +
			"up 5\n" +
			"down 1\n" +
			"forward 6\n" +
			"down 9\n" +
			"forward 5\n" +
			"up 2\n" +
			"up 9\n" +
			"down 6\n" +
			"down 8\n" +
			"down 6\n" +
			"up 1\n" +
			"forward 7\n" +
			"down 9\n" +
			"up 2\n" +
			"forward 3\n" +
			"down 7\n" +
			"up 5\n" +
			"forward 3\n" +
			"forward 8\n" +
			"up 2\n" +
			"forward 1\n" +
			"down 6\n" +
			"down 7\n" +
			"up 4\n" +
			"down 5\n" +
			"up 8\n" +
			"forward 9\n" +
			"forward 5\n" +
			"up 7\n" +
			"down 3\n" +
			"forward 2\n" +
			"up 7\n" +
			"up 2\n" +
			"down 3\n" +
			"up 9\n" +
			"down 9\n" +
			"down 8\n" +
			"up 8\n" +
			"down 6\n" +
			"forward 9\n" +
			"up 7\n" +
			"forward 4\n" +
			"forward 7\n" +
			"up 7\n" +
			"down 6\n" +
			"forward 5\n" +
			"up 2\n" +
			"up 4\n" +
			"down 1\n" +
			"down 2\n" +
			"down 9\n" +
			"forward 5\n" +
			"forward 3\n" +
			"forward 9\n" +
			"up 7\n" +
			"forward 7\n" +
			"down 5\n" +
			"down 2\n" +
			"up 9\n" +
			"forward 4\n" +
			"forward 4\n" +
			"up 5\n" +
			"up 3\n" +
			"forward 5\n" +
			"forward 9\n" +
			"forward 4\n" +
			"forward 8\n" +
			"down 2\n" +
			"up 4\n" +
			"down 1\n" +
			"forward 9\n" +
			"forward 9\n" +
			"up 7\n" +
			"down 3\n" +
			"forward 2\n" +
			"forward 4\n" +
			"down 6\n" +
			"up 1\n" +
			"forward 6\n" +
			"down 4\n" +
			"up 9\n" +
			"down 4\n" +
			"forward 3\n" +
			"down 9\n" +
			"up 9\n" +
			"down 8\n" +
			"up 6\n" +
			"forward 9\n" +
			"forward 1\n" +
			"forward 2\n" +
			"up 2\n" +
			"forward 8\n" +
			"forward 9\n" +
			"forward 3\n" +
			"forward 5\n" +
			"down 5\n" +
			"down 7\n" +
			"forward 7\n" +
			"forward 5\n" +
			"down 3\n" +
			"up 2\n" +
			"forward 4\n" +
			"down 3\n" +
			"up 6\n" +
			"down 6\n" +
			"up 6\n" +
			"forward 1\n" +
			"forward 2\n" +
			"down 5\n" +
			"down 8\n" +
			"down 3\n" +
			"forward 5\n" +
			"up 4\n" +
			"forward 6\n" +
			"forward 9\n" +
			"forward 6\n" +
			"forward 1\n" +
			"forward 4\n" +
			"up 1\n" +
			"forward 3\n" +
			"forward 3\n" +
			"up 3\n" +
			"forward 9\n" +
			"forward 1\n" +
			"forward 7\n" +
			"forward 8\n" +
			"forward 1\n" +
			"forward 9\n" +
			"forward 7\n" +
			"up 9\n" +
			"forward 9\n" +
			"up 4\n" +
			"down 4\n" +
			"up 9\n" +
			"down 5\n" +
			"down 8\n" +
			"down 3\n" +
			"forward 6\n" +
			"down 7\n" +
			"forward 5\n" +
			"forward 6\n" +
			"forward 8\n" +
			"forward 7\n" +
			"down 7\n" +
			"down 5\n" +
			"forward 4\n" +
			"down 6\n" +
			"down 4\n" +
			"down 6\n" +
			"down 1\n" +
			"forward 3\n" +
			"down 3\n" +
			"down 7\n" +
			"forward 6\n" +
			"forward 3\n" +
			"up 2\n" +
			"forward 1\n" +
			"forward 8\n" +
			"down 9\n" +
			"down 3\n" +
			"down 3\n" +
			"up 6\n" +
			"down 7\n" +
			"down 3\n" +
			"forward 2\n" +
			"down 7\n" +
			"down 2\n" +
			"forward 1\n" +
			"down 7\n" +
			"down 3\n" +
			"forward 9\n" +
			"down 4\n" +
			"down 3\n" +
			"forward 9\n" +
			"up 2\n" +
			"up 4\n" +
			"forward 4\n" +
			"down 4\n" +
			"up 2\n" +
			"down 2\n" +
			"forward 8\n" +
			"down 1\n" +
			"up 9\n" +
			"down 5\n" +
			"down 7\n" +
			"forward 3\n" +
			"forward 9\n" +
			"forward 7\n" +
			"forward 1\n" +
			"forward 7\n" +
			"forward 1\n" +
			"forward 7\n" +
			"up 7\n" +
			"down 6\n" +
			"forward 6\n" +
			"forward 4\n" +
			"forward 6\n" +
			"up 3\n" +
			"down 5\n" +
			"down 5\n" +
			"down 3\n" +
			"down 6\n" +
			"down 3\n" +
			"down 3\n" +
			"up 2\n" +
			"down 4\n" +
			"up 8\n" +
			"down 4\n" +
			"up 2\n" +
			"down 7\n" +
			"forward 9\n" +
			"up 9\n" +
			"down 1\n" +
			"forward 8\n" +
			"forward 7\n" +
			"forward 6\n" +
			"forward 8\n" +
			"up 6\n" +
			"up 6\n" +
			"down 5\n" +
			"forward 6\n" +
			"down 3\n" +
			"forward 6\n" +
			"forward 9\n" +
			"down 2\n" +
			"down 6\n" +
			"down 4\n" +
			"down 5\n" +
			"forward 7\n" +
			"forward 4\n" +
			"up 3\n" +
			"down 6\n" +
			"down 6\n" +
			"forward 1\n" +
			"forward 4\n" +
			"down 6\n" +
			"up 3\n" +
			"forward 1\n" +
			"down 3\n" +
			"down 7\n" +
			"down 4\n" +
			"down 8\n" +
			"down 8\n" +
			"up 8\n" +
			"down 2\n" +
			"up 8\n" +
			"down 3\n" +
			"down 3\n" +
			"forward 3\n" +
			"down 3\n" +
			"down 7\n" +
			"up 6\n" +
			"forward 8\n" +
			"down 4\n" +
			"forward 1\n" +
			"down 7\n" +
			"down 3\n" +
			"forward 5\n" +
			"forward 8\n" +
			"up 1\n" +
			"forward 2\n" +
			"down 7\n" +
			"down 7\n" +
			"forward 1\n" +
			"up 7\n" +
			"down 3\n" +
			"up 3\n" +
			"forward 5\n" +
			"forward 9\n" +
			"down 3\n" +
			"down 7\n" +
			"down 5\n" +
			"forward 7";

	static int horizontal = 0;
	static int depth = 0;
	static int aim = 0;

	public static void main(String... args) {
		for (int i = 0; i < input.split("\n").length; i++) {
			String str = input.split("\n")[i];
			if (str.startsWith("u")) {
				aim = aim - AdventOfCodeUtil.getFirstNumberOfString(str);
			}

			if (str.startsWith("d")) {
				aim = aim + AdventOfCodeUtil.getFirstNumberOfString(str);
			}

			if (str.startsWith("f")) {
				horizontal = horizontal + AdventOfCodeUtil.getFirstNumberOfString(str);
				depth = depth + aim * AdventOfCodeUtil.getFirstNumberOfString(str);
			}


			System.out.println(horizontal * depth);
		}
	}

}
